'use client'
import dynamic from 'next/dynamic'
import { useLayoutEffect, useRef } from 'react'
import { gsap } from 'gsap'
const HeroGL = dynamic(() => import('./HeroGL'), { ssr: false })
export default function Hero(){ const labelRef=useRef<HTMLDivElement>(null); const charsRef=useRef<HTMLDivElement>(null); const lineRef=useRef<HTMLDivElement>(null); useLayoutEffect(()=>{ const chars = charsRef.current?.querySelectorAll('.char') ?? []; gsap.set(chars,{y:'100%'}); const tl=gsap.timeline(); tl.fromTo(labelRef.current,{y:20,opacity:0},{y:0,opacity:1,duration:0.8,ease:'power3.out'},0).to(chars,{y:'0%',duration:0.9,stagger:0.025,ease:'power4.out'},0.3); gsap.fromTo(lineRef.current,{scaleY:0},{scaleY:1,duration:1.4,repeat:-1,yoyo:true,transformOrigin:'top center',ease:'power2.inOut'}) },[])
const lines=['WE GIVE','SHAPE TO','IDEAS.'];
const split=(text:string)=>text.split('').map((c,i)=><span className="char-wrap" key={i}><span className="char">{c===' '?'\u00A0':c}</span></span>)
return <section style={{minHeight:'100svh',position:'relative',display:'flex',flexDirection:'column',justifyContent:'flex-end',padding:'0 48px 80px'}}><HeroGL/><div ref={labelRef} style={{position:'absolute',top:100,left:48,color:'var(--muted)'}} className="text-label">DIGITAL EXPERIENCE STUDIO — EST. MMXXV</div><div style={{position:'relative',zIndex:1,display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:24}}><div ref={charsRef} className="font-display text-hero" style={{color:'var(--off-white)'}}>{lines.map((l,idx)=><div key={idx}>{split(l)}</div>)}</div><p style={{maxWidth:280,fontSize:15,color:'var(--muted)',lineHeight:1.7}}>From brand identities that breathe to digital experiences that refuse to be forgotten — FORMA shapes the immaterial into the inevitable.</p></div><div style={{position:'absolute',bottom:18,left:'50%',transform:'translateX(-50%)',display:'flex',flexDirection:'column',alignItems:'center',gap:8,zIndex:1}}><span className="text-label" style={{color:'var(--muted)'}}>SCROLL</span><div ref={lineRef} style={{width:1,height:60,background:'var(--lime)'}}/></div></section>}
